import type { ThemeDef } from '../../engine/plugin'
import { SPRITES } from './sprites'

export const classicTheme: ThemeDef = {
  id: 'classic',
  rooms: [
    'Library',
    'Kitchen',
    'Cellar',
    'Attic',
    'Garden',
    'Study',
    'Gallery',
    'Conservatory',
    'Parlor',
    'Workshop',
    'Pantry',
    'Balcony',
    'Laundry',
    'Cloakroom',
    'Observatory',
    'Chapel',
  ],
  suspects: [
    'Ada',
    'Bram',
    'Cora',
    'Dev',
    'Elsa',
    'Finn',
    'Gus',
    'Hana',
    'Ivo',
    'June',
    'Kai',
    'Lena',
    'Milo',
    'Nora',
    'Otto',
    'Pia',
  ],
  objects: {
    chair: { noun: 'a chair', standingOn: 'sitting on a chair', sprite: SPRITES.chair, weight: 0.1 },
    rug: { noun: 'a rug', standingOn: 'on a rug', sprite: SPRITES.rug, weight: 0.06 },
    water: { noun: 'the water', standingOn: 'in the water', sprite: SPRITES.water, weight: 0.04 },
    table: { noun: 'a table', standingOn: 'on a table', sprite: SPRITES.table, weight: 0.05 },
    shelf: { noun: 'a shelf', standingOn: 'on a shelf', sprite: SPRITES.shelf, weight: 0.03 },
    plant: { noun: 'a plant', standingOn: 'on a plant', sprite: SPRITES.plant, weight: 0.03 },
    rock: { noun: 'a rock', standingOn: 'on a rock', sprite: SPRITES.rock, weight: 0.02 },
    tree: { noun: 'a tree', standingOn: 'on a tree', sprite: SPRITES.tree, weight: 0.02 },
    tv: { noun: 'a TV', standingOn: 'on a TV', sprite: SPRITES.tv, weight: 0.01 },
  },
}
