import type { ThemeDef } from '../../engine/plugin'
import { SPRITES } from './sprites'

export const classicTheme: ThemeDef = {
  id: 'classic',
  rooms: [
    'Library',
    'Kitchen',
    'Cellar',
    'Attic',
    'Garden',
    'Study',
    'Gallery',
    'Conservatory',
    'Parlor',
    'Workshop',
    'Pantry',
    'Balcony',
    'Laundry',
    'Cloakroom',
    'Observatory',
    'Chapel',
  ],
  suspects: [
    'Ada',
    'Bram',
    'Cora',
    'Dev',
    'Elsa',
    'Finn',
    'Gus',
    'Hana',
    'Ivo',
    'June',
    'Kai',
    'Lena',
    'Milo',
    'Nora',
    'Otto',
    'Pia',
  ],
  objects: {
    chair: { label: 'Chair', noun: 'a chair', standingOn: 'sitting on a chair', sprite: SPRITES.chair, weight: 0.1 },
    rug: { label: 'Rug', noun: 'a rug', standingOn: 'on a rug', sprite: SPRITES.rug, weight: 0.06 },
    water: { label: 'Water', noun: 'the water', standingOn: 'in the water', sprite: SPRITES.water, weight: 0.04 },
    table: { label: 'Table', noun: 'a table', standingOn: 'on a table', sprite: SPRITES.table, weight: 0.05 },
    shelf: { label: 'Shelf', noun: 'a shelf', standingOn: 'on a shelf', sprite: SPRITES.shelf, weight: 0.03 },
    plant: { label: 'Plant', noun: 'a plant', standingOn: 'on a plant', sprite: SPRITES.plant, weight: 0.03 },
    rock: { label: 'Rock', noun: 'a rock', standingOn: 'on a rock', sprite: SPRITES.rock, weight: 0.02 },
    tree: { label: 'Tree', noun: 'a tree', standingOn: 'on a tree', sprite: SPRITES.tree, weight: 0.02 },
    tv: { label: 'TV', noun: 'a TV', standingOn: 'on a TV', sprite: SPRITES.tv, weight: 0.01 },
  },
  glossary: {
    not: 'The opposite is true: this is where they were not.',
    beside: 'Directly left, right, above or below something, in the same room. Diagonals do not count.',
    'north of': 'In a row above, counting rows from the top of the board. The number says how many rows apart.',
    'west of': 'In a column to the left. The number says how many columns apart.',
    'same room': 'Both were inside the same room, in different squares.',
    alone: 'Nobody else was in the same room.',
    only: 'Nobody else stood on that kind of object.',
    'exactly one other': 'Exactly two people, counting them, were in the room.',
    'alone with the killer': 'The victim and the killer were the only two people in the room.',
  },
}
